### ISSUE TITLE
cloud-raymarching-walkthrough-part1

### ISSUE THREAD

**Issue by KANAjetzt** [DavidPeicho/davidpeicho.github.io#23]
Thanks a lot for this great article.
Just some quick feedback or issues I had.

<details >
<summary>Hardcoded camera position</summary>
For some reason I had to set the camera position in the vertex shader to 0 0 0 to get the expected result:

I got this with `vec3 cameraPosition = vec3(0.0, 0.0, 2.0);` :
![image](https://user-images.githubusercontent.com/41547570/141456678-2443eeb6-3806-49b5-9c47-c0d8fde9b2e8.png)

And this with `vec3 cameraPosition = vec3(0.0, 0.0, 0.0);` :
![image](https://user-images.githubusercontent.com/41547570/141456792-50a416ec-d5c2-4df1-acbf-bc2cb9fa22a0.png)

My camera setup is this:

```
/**
 * Camera
 */
// Base camera
const camera = new THREE.PerspectiveCamera(
  45,
  sizes.width / sizes.height,
  0.1,
  100
);

camera.position.z = 2.0;

scene.add(camera);
```

![image](https://user-images.githubusercontent.com/41547570/141457184-3fb9976a-4146-4c3d-acff-b1b11dc85710.png)

Hear I had to switch back to  `vec3 cameraPosition = vec3(0.0, 0.0, 2.0);`  🤔
</details>

<details open>
<summary>NB_STEPS</summary>
`NB_STEPS` just came out of nowhere so I had trouble to understand what to do with it. 😅</br>
Until I checked your code on github. 👍
</details>

**Comment by DavidPeicho** [comment]
Hey! Thanks for the heads up. Your first screenshot good 👍  I think I took a screenshot with a different size for the box geometry or something. I will update that.

Thanks as well for the `NB_STEPS` define, it's fixed and explained in the course now!

I will publish tonight an erratum
