### ISSUE TITLE
[TEACHING] Erreur PDF / Slides

### ISSUE THREAD

**Issue by erwanvivien** [DavidPeicho/davidpeicho.github.io#28]
https://davidpeicho.github.io/teaching/rendering/pbr.pdf

Sur ce PDF, page 28: "Incident Light" => "Reflected Light"

**Comment by erwanvivien** [comment]
Slide 31, renommer radiance en irradiance

**Comment by DavidPeicho** [comment]
Thanks. Slide 40 forgot to mult by `1 - metallic` as well

**Comment by erwanvivien** [comment]
Slide 73, the color for `Output 1 scale` should be red and `Output 2 bias` should be green

**Comment by erwanvivien** [comment]
Slide 70, should be F0 * texture_red * texture_green ?

**Comment by erwanvivien** [comment]
Slide 77, duplicate link

**Comment by DavidPeicho** [comment]
Fixed. I will push in 5 minutes. Thanks!
